[2019-Dec-07 21:44] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:45] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:45] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:46] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:46] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:46] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:49] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:49] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:49] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:53] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:53] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:53] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:59] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:59] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:59] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 21:59] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 21:59] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 21:59] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:05] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:05] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:08] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:08] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:08] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:09] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:09] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:09] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:11] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:11] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:11] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:11] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:11] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:11] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:12] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:12] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:12] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:13] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:13] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:13] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:13] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:13] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:13] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:18] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:18] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:18] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:30] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:30] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:34] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:34] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:37] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:37] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:37] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:37] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:38] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:38] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:38] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:39] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:39] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:39] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:39] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:39] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:39] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:41] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 22:42] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 22:42] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 22:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

