[2019-Dec-13 22:25] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:26] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:30] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:30] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:36] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:36] 127.0.0.1 GET http /network? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 355, in d3_network
    return render_template('network.html', json_data = json_data)
NameError: name 'json_data' is not defined

[2019-Dec-13 22:36] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /d3_data? 200 OK
[2019-Dec-13 22:38] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:40] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:40] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:41] 127.0.0.1 GET http /fetch_random_data? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:41] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /d3_data? 200 OK
[2019-Dec-13 22:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:51] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:51] 127.0.0.1 GET http /d3_data? 200 OK
[2019-Dec-13 22:51] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:52] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /d3_data? 200 OK
[2019-Dec-13 22:52] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

