[2019-Dec-13 21:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:22] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:22] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:23] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:23] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:24] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:24] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:25] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:25] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:25] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:25] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:25] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:28] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:28] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:28] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:34] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:34] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:35] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:36] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:36] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:41] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:41] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:42] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:42] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:43] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:43] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:45] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:45] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:46] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:46] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:47] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:47] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:49] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:49] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:51] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:51] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:52] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:52] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:53] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:53] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:54] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:57] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 21:57] 127.0.0.1 GET http /d3_data.json? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 21:57] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:00] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /d3_data.json? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:00] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:00] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:00] 127.0.0.1 GET http /d3_data.json? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:00] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:01] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:01] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:02] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:02] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:04] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:04] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:05] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:05] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:06] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:06] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:06] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:07] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:08] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:08] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:08] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:08] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:08] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:12] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:12] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:12] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:12] 127.0.0.1 GET http /network.html? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:12] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:13] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:13] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:14] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:14] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:15] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:15] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:17] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:17] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:18] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:18] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-13 22:20] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:20] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:22] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:24] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-13 22:24] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-13 22:25] 127.0.0.1 GET http /network? 200 OK
