[2019-Dec-07 16:20] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:20] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:20] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 16:20] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:20] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:20] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:22] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:26] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:26] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 16:26] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:27] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 16:27] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:47] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 16:47] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:48] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 16:48] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:56] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 16:56] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 487, in tree_view
    data.sorted(key=(lambda x: x["card_id"]))
AttributeError: 'list' object has no attribute 'sorted'

[2019-Dec-07 16:56] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 16:58] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 16:58] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 17:01] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 17:01] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 17:02] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 17:13] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 17:13] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:10] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:10] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 491, in tree_view
    slot_number = data[0][['card_id'].split("/")[0]]
AttributeError: 'list' object has no attribute 'split'

[2019-Dec-07 18:10] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:11] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:11] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 491, in tree_view
    slot_number = data[0][['card_id'].split("/")[0]]
AttributeError: 'list' object has no attribute 'split'

[2019-Dec-07 18:11] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:12] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:12] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 496, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:12] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:15] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-07 18:15] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 497, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:15] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:16] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:16] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 497, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:16] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:17] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:17] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 497, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:17] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:18] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:18] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 498, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:18] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:19] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:19] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 499, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:19] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:21] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:21] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:23] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:23] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:24] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:24] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:24] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:25] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:25] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.sort(key=(lambda x: int(x["card_id"].split("/")[1])))
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:25] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:26] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:26] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.append(item)
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:26] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:30] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:30] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.append(item)
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:31] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:31] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.append(item)
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:32] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:32] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 500, in tree_view
    card_slot_array.append(item)
UnboundLocalError: local variable 'card_slot_array' referenced before assignment

[2019-Dec-07 18:32] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:33] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:33] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:34] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:41] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:41] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:42] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 511, in tree_view
    print("size after ----->", sizeof(data_sorted))
NameError: name 'sizeof' is not defined

[2019-Dec-07 18:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:42] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:42] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 511, in tree_view
    print("size after ----->", size(data_sorted))
NameError: name 'size' is not defined

[2019-Dec-07 18:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:43] 127.0.0.1 GET http /? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:43] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:44] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:44] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:51] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:51] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 18:53] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 18:53] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:05] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:05] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:05] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:05] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:08] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:08] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:09] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:09] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:21] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:21] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:21] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:21] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:22] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:22] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:22] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:35] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:35] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:36] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 517, in tree_view
    return render_template('tree_view.html', data=data_sorted)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/root/flask/PythonFlaskjQueryAjax/templates/tree_view.html", line 39, in template
    {%endfor%}
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.

[2019-Dec-07 19:36] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:37] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:37] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:37] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:39] 127.0.0.1 GET http /tree_view? 200 OK
[2019-Dec-07 19:39] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-07 19:47] 127.0.0.1 GET http /tree_view? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 496, in tree_view
    return render_template('tree_view.html', data=data_sorted)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/root/flask/PythonFlaskjQueryAjax/templates/tree_view.html", line 40, in template
    {{slot_number = item['card_id'].split('/')[0]}}
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 199, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "/home/jon/venv/p3/lib/python3.6/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='

[2019-Dec-07 19:47] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

