[2019-Dec-20 20:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:42] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:45] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:49] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 20:49] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 21:28] 127.0.0.1 GET http /? 200 OK
[2019-Dec-20 21:34] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-20 21:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 21:34] 127.0.0.1 GET http /? 200 OK
[2019-Dec-20 22:04] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-20 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-20 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-20 22:04] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-20 22:04] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-20 22:04] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/auto-complete.css? 304 NOT MODIFIED
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/signin.css? 304 NOT MODIFIED
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/fetch.js? 304 NOT MODIFIED
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/scss_css.css? 304 NOT MODIFIED
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/my_style.css? 304 NOT MODIFIED
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /easyui? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/easyui.css? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/icon.css? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/demo.css? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/jquery.easyui.min.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/js/jquery.min.js? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/images/combo_arrow.png? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /static/css/images/blank.gif? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 976, in send_static_file
    cache_timeout=cache_timeout)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/helpers.py", line 709, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 20:54] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /network3? 200 OK
[2019-Dec-26 20:54] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:18] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /static/css/d3_css.css? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:19] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /static/css/bootstrap.min.css? 200 OK
[2019-Dec-26 21:19] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:30] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 21:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:30] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:31] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:33] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:33] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 21:33] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:33] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:34] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:34] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:34] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 21:34] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 21:34] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:35] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:35] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:35] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:38] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:38] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:46] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:46] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:48] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:48] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:49] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:49] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:53] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:53] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:55] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:55] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 21:55] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 21:58] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 21:58] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /d3? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /network? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /d3_data? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 22:03] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /doc? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /hello? 200 OK
[2019-Dec-26 22:03] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:04] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /multi? 200 OK
[2019-Dec-26 22:05] 127.0.0.1 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/jon/venv/p3/lib/python3.6/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/jon/venv/p3/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

[2019-Dec-26 22:05] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:07] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:07] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:08] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/auto-complete.css? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/signin.css? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/my_style.css? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/js/jquery-1.9.0.js? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/js/script.js? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/js/fetch.js? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/scss_css.css? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/js/auto-complete.min.js? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/data/data.json? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/js/autocomplete.js? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:10] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:16] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:16] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:16] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:17] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:17] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:17] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:19] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:19] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:19] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:21] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:21] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:22] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:22] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:22] 127.0.0.1 GET http /? 200 OK
[2019-Dec-26 22:22] 127.0.0.1 GET http /static/favicon.ico? 200 OK
[2019-Dec-26 22:23] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
[2019-Dec-26 22:24] 127.0.0.1 GET http /static/css/scss_css.css.map? 200 OK
